/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AcceptEther",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AcceptEther__factory>;
    getContractFactory(
      name: "AcceptEtherWithLog",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AcceptEtherWithLog__factory>;
    getContractFactory(
      name: "AccountContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccountContract__factory>;
    getContractFactory(
      name: "CallExample",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CallExample__factory>;
    getContractFactory(
      name: "GasExample",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GasExample__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;
    getContractFactory(
      name: "VariableStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VariableStorage__factory>;

    getContractAt(
      name: "AcceptEther",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AcceptEther>;
    getContractAt(
      name: "AcceptEtherWithLog",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AcceptEtherWithLog>;
    getContractAt(
      name: "AccountContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccountContract>;
    getContractAt(
      name: "CallExample",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CallExample>;
    getContractAt(
      name: "GasExample",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GasExample>;
    getContractAt(
      name: "Greeter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Greeter>;
    getContractAt(
      name: "VariableStorage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VariableStorage>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
